title: How to sow your seed
tags: sgl, vertical, soil
reftime: 1-2
intro:
  image:
    url: assets/pic.png
    layout: left
  text: |
    Now that the seed has sprouted time to **sow** it in it's first pot :)
    1. Water the soil
    2. Make a hole with your finger or a pen about 1 nail deep
    3. Carfuly place the seed and cover it up with soil

products:
  - name: Light mix soil
    urls:
      - zone: EU
        image: assets/monkey_soil.png
        url: https://www.monkeysoil.com/en/product/light-mix-evolution/

reminders:
  - delay: 1d
    text: The main predator of young seedlings? Over-watering. Check how to not kill your plant.
    next: 10_veg/20_mid/10_when_to_water_seedling

triggers:
  - id: TEMPERATURE
    notification: TODO
    metric: TEMP
    value: 21-32
  - id: HUMIDITY
    notification: TODO
    metric: HUMI
    value: 40-70
