title: When to harvest
tags:
  - sgl
  - vertical
  - soil
reftime: 98-105
intro:
  image:
    url: when_to_harvest.png
    layout: left
  text: |
    Trichomes are the best indicator for cannabis maturity, use them as your guide to harvest:
    clear and translucent: immature
    cloudy and translucent: energetic high
    cloudy and amber: body high
    Check on them every couple of days until you find your prefered ratio.

products:
  - name: Jewler's loupe x60
    urls:
      - zone: US
        image: jewler_loupe.png
        url: https://amzn.to/32ILSBb

  - name: Handheld microscope x60-x120
    urls:
      - zone: US
        image: microscope.png
        url:   https://amzn.to/32JLceX

  - name: Trimming scisors
    urls:
      - zone: US
        image: trimming_scisors.png
        url: https://amzn.to/2x3yz2A

  - name: Trim bin
    urls:
      - zone: US
        image: trimming_bin.png
        url: https://amzn.to/2VJw6EV

triggers:
  - id: TEMPERATURE
    notification: TODO
    metric: TEMP
    value_day: 21-24
    value_night: 17-21
  - id: HUMIDITY
    notification: TODO
    metric: HUMI
    value: 30-40