title: How to sow your seed
tags:
  - sgl
  - vertical
  - soil
reftime: 1-2
intro:
  image:
    url: assets/how_to_sow_seed.png
    layout: left
  text: |
    The seed has sprouted! Time to **sow** it in it's first pot :)
    1. Put 1 layer of clay balls in the small pot
    1. Add soil, water it, repeat until the soil almost reaches the top
    *note: this 'lip' will prevent water from overflowing when watering*
    2. Make a hole with your finger or a pen 1 fingernail deep
    3. Carfuly place the seed, cover it up with soil and tamp lightly
    4. Mist/hydrate lightly twice daily to keep moisture up
    5. Consider adding a transparent dome to increase humidity if your is low (RH<50%)

products:
  
  - name: Light mix soil
    urls:
      - zone: DE
        image: assets/light_mix.png
        url: https://amzn.to/2IPzaHF
  
  - name: Clay balls
    urls:
      - zone: DE
        image: assets/clay_balls.png
        url: https://amzn.to/2WfA2gC
  
  - name:   Small pot
    urls:
      - zone: DE
        image: assets/small_pot.png
        url: https://amzn.to/2voqPaP



reminders:
  - delay: 1d
    text: The main predator of young seedlings? Over-watering. Check how to not kill your plant.
    next: 10_veg/20_mid/10_when_to_water_seedling

triggers:
  - id: TEMPERATURE
    notification: TODO
    metric: TEMP
    value_day: 21-32
    value_night: 17-28
  - id: HUMIDITY
    notification: TODO
    metric: HUMI
    value: 40-70
