title: How to sow your seed
tags:
  - sgl
  - vertical
  - soil
reftime: 1-2
intro:
  image:
    url: assets/how_to_sow_seed.png
    layout: left
  text: |
    The seed has sprouted! Time to **sow** it in it's first pot :)
    1. Put a layer of clay balls in the small pot
    1. Add soil and water it
    2. Make a hole with your finger or a pen 1/2 fingernail deep
    3. Carfuly place the seed, cover it up with soil and tamp lightly

products:
  - name: Light mix soil
    urls:
      - zone: EU
        image: assets/monkey_soil.png
        url: https://www.monkeysoil.com/en/product/light-mix-evolution/
  - name: Clay balls
    urls:
      - zone: EU
        image: assets/clay_balls.png
        url: https://www.amazon.de/dp/B07KK9ZPRZ
  - name: Small pot
      - zone: EU
        image: assets/small_pot.png
        url: https://www.amazon.de/dp/B07KK9ZPRZ

reminders:
  - delay: 1d
    text: The main predator of young seedlings? Over-watering. Check how to not kill your plant.
    next: 10_veg/20_mid/10_when_to_water_seedling

triggers:
  - id: TEMPERATURE
    notification: TODO
    metric: TEMP
    value_day: 21-32
    value_night: 17-28
  - id: HUMIDITY
    notification: TODO
    metric: HUMI
    value: 40-70
