title: How to switch to bloom
tags:
  - sgl
  - vertical
  - soil
reftime: 35-42
intro:
  image:
    url: how_to_switch_to_bloom.png
    layout: left
  text: |
    12 hours of uninterupted darkness is what will start the flowering process.
    With the press of a button on the SuperGreenLab app, the controller switches the vegetative 18/6 light cycle to the flowering 12/12.

triggers:
  - id: TEMPERATURE
    notification: TODO
    metric: TEMP
    value_day: 21-26
    value_night: 17-24
  - id: HUMIDITY
    notification: TODO
    metric: HUMI
    value: 40-55